### ISSUE TITLE
performance issues yq

### ISSUE THREAD

**Issue by Morriz** [redkubes/otomi-core#261]
The 5 bats tests are not performing well. They should run under 5 seconds imo. Can this be optimized?

**Comment by svatwork** [comment]
Yes, I agree. It can be optimized, I wasn't sure if it was inside the scope in #203.

I have some ideas:
- Test everything from `bootstrap.sh` in one function, but this reduces test coverage.
- The true bottleneck is in what is being tested in `bootstrap.sh`. Currently, it's just one big script. We could write functions for the logic being tested and test those functions separately.
- The Github Actions runner could run on a dedicated server with more horsepower.
- For some of the logic in `bootstrap.sh`, it's not quite DRY. I think the original intention was to setup everything for the first time, which makes sense. However, I'm also quite annoyed by the performance of this script, so I've just sym-linked the files I need into my `otomi-values` repo and now I never run it.

**Comment by Morriz** [comment]
Nah, you are overthinking it as the script only copies some files. Please understand that symlinking is for devs only, so no solution here. We need to time the operations. Is the file mount on the container inducing so much latency when it comes to copying? Instrument the code to show times with `-x` or something

**Comment by Morriz** [comment]
I think we have to look into decryption. Is that happening every call?

**Comment by svatwork** [comment]
The latency in `bin/bootstrap.sh` occurs over here:

```
+ yq d - properties.toolsVersion
+ yq d /Users/sebastiaanverbeek/Projects/redkubes/dev/otomi-core/values-schema.yaml '**.required.'
+ yq d - properties.cluster
****LATENCY****
+ '[' /Users/sebastiaanverbeek/Projects/redkubes/dev/otomi-core '!=' /home/app/stack ']'
+ cp ./env/.vscode/values-schema.yaml .values/
+ echo 'Stored JSON schema at: ./env/.vscode/values-schema.yaml'
```
I added that line with 'LATENCY' of course. I don't know what to make of it though.

**Comment by svatwork** [comment]
Reproduce it by:

```
local targetPath="$ENV_DIR/.vscode/values-schema.yaml"                                                       
  local sourcePath="$PWD/values-schema.yaml"
  yq d $sourcePath '**.required.' | yq d - 'properties.toolsVersion' | yq d - 'properties.cluster' >$targetPath
```

**Comment by svatwork** [comment]
Related: https://github.com/mikefarah/yq/issues/422

**Comment by j-zimnowoda** [comment]
I see that  mikefarah/yq#422 is solved. Releases after 12.06.2020 should not have performance issue.

**Comment by svatwork** [comment]
Well apparently there was a version where this wasn't an issue: "after downgrade to yq 2.4.1 --> zippy fast again (ie: 30s to parse yaml file in 3.x became sub second response time with 2.4.1)"

**Comment by svatwork** [comment]
> The otomi-tools is using version 3.3.2, why do you think that downgrading yq will improve performance?

Well the issue isn't solved in 3.3.4 which is what I'm running:
```yq -V                          
yq version 3.4.1
```

**Comment by svatwork** [comment]
Let's wait for #269 as discussed in Slack.

**Comment by Dunky13** [comment]
#271 Doesn't solve it, does the following command work:
`yq r -j $sourcePath | jq "del(.. | .required?)" | jq "del( .properties.toolsVersion? )" | jq "del( .properties.cluster)" | yq r --prettyPrint -`
Could use a little polishing, maybe combine the jq commands into one?

**Comment by svatwork** [comment]
Yes, if these are equivalent then it this is a solution, the performance is fine now. Do you want to create a pr?

**Comment by Dunky13** [comment]
Maybe this works: `yq r -j $sourcePath | jq "del(.. | .required?) | del( .properties.toolsVersion? ) | del( .properties.cluster)" | yq r --prettyPrint -`

**Comment by svatwork** [comment]
Works great too.

**Comment by Morriz** [comment]
@Dunky13 can you create that PR then so we can benefit soon?

**Comment by Dunky13** [comment]
> @Dunky13 can you create that PR then so we can benefit soon?

PR is open, ready for check & merge
